# Generated by Django 2.2.1 on 2019-05-30 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAcquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Registry', 'Registry'), ('Upload', 'Upload'), ('Interactive', 'Interactive')], max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('Finished', 'Finished'), ('Processing', 'Processing')], default='Processing', editable=False, max_length=63)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acquisition_file', models.FileField(upload_to='%Y/%m/%d/')),
                ('acquisition_report', models.FileField(editable=False, upload_to='%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Failure', 'Failure')], max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$'), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Append', 'Append'), ('Replace', 'Replace'), ('Delete', 'Delete')], default='A', max_length=63)),
                ('structure_location', models.URLField(null=True)),
                ('external_dependencies', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('abstractacquisition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.AbstractAcquisition')),
            ],
            bases=('registry.abstractacquisition',),
        ),
        migrations.CreateModel(
            name='SubmittedStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('Append', 'Append'), ('Replace', 'Replace'), ('Delete', 'Delete')], max_length=63, null=True)),
                ('external_dependencies', models.BooleanField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('status_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.StatusMessage')),
                ('structure_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_structures', to='registry.Structure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=63, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-z0-9_@$\\-]+$'), 'Enter a value of type IDType that has pattern "(^[A-Za-z0-9_@$\\-]+$)"', 'invalid_pattern')], verbose_name='ID')),
                ('test', models.BooleanField(default=False)),
                ('prepared', models.DateTimeField(blank=True, editable=False, null=True)),
                ('receiver', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_submissions', to='base.Organisation')),
                ('receiver_contacts', models.ManyToManyField(editable=False, related_name='receiver_contact_submissions', to='base.Contact')),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender_submissions', to='base.Organisation')),
                ('sender_contacts', models.ManyToManyField(editable=False, related_name='sender_contact_submissions', to='base.Contact')),
                ('acquistion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='registry.Acquisition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_submission', to='registry.Submission'),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='message_text',
            field=models.ManyToManyField(to='registry.StatusMessageText'),
        ),
        migrations.CreateModel(
            name='RESTfulRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prepared', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(max_length=63)),
                ('agency_id', models.CharField(max_length=63)),
                ('resource_id', models.CharField(max_length=63)),
                ('version', models.CharField(max_length=63)),
                ('detail', models.CharField(max_length=63)),
                ('references', models.CharField(max_length=63)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wsrest_structure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
