# Generated by Django 2.2.6 on 2019-10-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=31, verbose_name='ID')),
                ('annotation_title', models.CharField(blank=True, max_length=127, verbose_name='title')),
                ('annotation_type', models.CharField(blank=True, max_length=31, verbose_name='type')),
                ('annotation_url', models.URLField(blank=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('text_el', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.IntegerField(choices=[(0, 'String'), (1, 'Alpha'), (2, 'AlphaNumeric'), (3, 'Numeric'), (4, 'BigInteger'), (5, 'Integer'), (6, 'Long'), (7, 'Short'), (8, 'Decimal'), (9, 'Float'), (10, 'Double'), (11, 'Boolean'), (12, 'URI'), (13, 'Count'), (14, 'InclusiveValueRange'), (15, 'ExclusiveValueRange'), (16, 'Incremental'), (17, 'ObservationalTimePeriod'), (18, 'StandardTimePeriod'), (19, 'BasicTimePeriod'), (20, 'GregorianTimePeriod'), (21, 'GregorianYear'), (22, 'GregorianYearMonth'), (23, 'GregorianDay'), (24, 'ReportingTimePeriod'), (25, 'ReportingYear'), (26, 'ReportingSemester'), (27, 'ReportingTrimester'), (28, 'ReportingQuarter'), (29, 'ReportingMonth'), (30, 'ReportingWeek'), (31, 'ReportingDay'), (32, 'DateTime'), (33, 'TimeRange'), (34, 'Month'), (35, 'MonthDay'), (36, 'Day'), (37, 'Time'), (38, 'Duration')], default=0, verbose_name='Text type')),
                ('is_sequence', models.BooleanField(blank=True, null=True, verbose_name='Is sequence')),
                ('interval', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Interval')),
                ('start_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Start value')),
                ('end_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='End value')),
                ('time_interval', models.DurationField(blank=True, null=True, verbose_name='Time interval')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum length')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum length')),
                ('min_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Minimum value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Maximum value')),
                ('decimals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Decimals')),
                ('pattern', models.TextField(blank=True, null=True, verbose_name='Pattern')),
                ('is_multi_lingual', models.BooleanField(blank=True, null=True, verbose_name='Is multi lingual')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferencePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Reference period',
                'verbose_name_plural': 'Reference periods',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URLString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.URLField(db_index=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='codelist.CodelistReference', verbose_name='Codelist reference')),
                ('enumeration_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.Format', verbose_name='Enumeration format')),
                ('text_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.Format', verbose_name='Text format')),
            ],
            options={
                'verbose_name': 'Representation',
                'verbose_name_plural': 'Representations',
                'abstract': False,
            },
        ),
    ]
