# Generated by Django 3.0b1 on 2019-10-29 18:12

from django.db import migrations, models
import django.db.models.deletion
import versionfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.IntegerField(choices=[(0, 'String'), (1, 'Alpha'), (2, 'AlphaNumeric'), (3, 'Numeric'), (4, 'Big integer'), (5, 'Integer'), (6, 'Long'), (7, 'Short'), (8, 'Decimal'), (9, 'Float'), (10, 'Double'), (11, 'Boolean'), (12, 'URI'), (13, 'Count'), (14, 'Inclusive value range'), (15, 'Exclusive value range'), (16, 'Incremental'), (17, 'Observational time period'), (18, 'Standard time period'), (19, 'Basic time period'), (20, 'Gregorian time period'), (21, 'Gregorian year'), (22, 'Gregorian year month'), (23, 'Gregorian month'), (24, 'Gregorian day'), (25, 'Reporting time period'), (26, 'Reporting year'), (27, 'Reporting semester'), (28, 'Reporting trimester'), (29, 'Reporting quarter'), (30, 'Reporting month'), (31, 'Reporting week'), (32, 'Reporting day'), (33, 'Date time'), (34, 'Time range'), (35, 'Month'), (36, 'Month day'), (37, 'Day'), (38, 'Time'), (39, 'Duration')], default=0, verbose_name='Text type')),
                ('is_sequence', models.BooleanField(blank=True, null=True, verbose_name='Is sequence')),
                ('interval', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Interval')),
                ('start_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Start value')),
                ('end_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='End value')),
                ('time_interval', models.DurationField(blank=True, null=True, verbose_name='Time interval')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum length')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum length')),
                ('min_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Minimum value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Maximum value')),
                ('decimals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Decimals')),
                ('pattern', models.TextField(blank=True, null=True, verbose_name='Pattern')),
                ('is_multi_lingual', models.BooleanField(blank=True, null=True, verbose_name='Is multi lingual')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_version', versionfield.VersionField(blank=True, null=True)),
                ('enumeration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='codelist.Codelist', verbose_name='Codelist reference')),
                ('enumeration_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.Format', verbose_name='Enumeration format')),
                ('text_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.Format', verbose_name='Text format')),
            ],
            options={
                'verbose_name': 'Representation',
                'verbose_name_plural': 'Representations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Name')),
                ('name_en', models.CharField(max_length=63, null=True, verbose_name='Name')),
                ('name_el', models.CharField(max_length=63, null=True, verbose_name='Name')),
                ('department', models.CharField(max_length=63, verbose_name='Department')),
                ('department_en', models.CharField(max_length=63, null=True, verbose_name='Department')),
                ('department_el', models.CharField(max_length=63, null=True, verbose_name='Department')),
                ('role', models.CharField(max_length=63, verbose_name='Role')),
                ('role_en', models.CharField(max_length=63, null=True, verbose_name='Role')),
                ('role_el', models.CharField(max_length=63, null=True, verbose_name='Role')),
                ('telephone', models.CharField(max_length=127, verbose_name='Telephone')),
                ('fax', models.CharField(max_length=127, verbose_name='Fax')),
                ('X400', models.CharField(max_length=127, verbose_name='X400')),
                ('email', models.CharField(max_length=127, verbose_name='Email')),
                ('uri', models.CharField(max_length=127, verbose_name='URI')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_set', related_query_name='contact', to='base.Agency', verbose_name='Agency')),
                ('data_consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_set', related_query_name='contact', to='base.DataConsumer', verbose_name='Data consumer')),
                ('data_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_set', related_query_name='contact', to='base.DataProvider', verbose_name='Data provider')),
                ('organisation_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_set', related_query_name='contact', to='base.OrganisationUnit', verbose_name='Organisation unit')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'abstract': False,
            },
        ),
    ]
