language: python
cache: pip
dist: xenial
matrix:
    include:
      - python: "3.7"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - rm -r django-fiesta.egg-info  # see #6139
          - tox --installpkg ./dist/django-fiesta-*.whl
          - tox  # test sdist


install:
    - pip install tox tox-venv tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV

notifications:
    email: false
