# Generated by Django 2.2.3 on 2019-09-10 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationscheme',
            name='submitted_structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.SubmittedStructure'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='wrappers',
            field=models.ManyToManyField(to='base.OrganisationScheme'),
        ),
        migrations.AddField(
            model_name='fax',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contact'),
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organisation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['object_id'], name='base_organi_object__63a41d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='base_contac_user_id_4f44c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'organisation'], name='base_contac_user_id_edc90e_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_org_contact'),
        ),
    ]
