FIESTA: 
  SENDER_ID: DJANGO-SDMX
FIESTA_MAXLENGTHS:
  OBJECT_ID: 63
  NAME: 255
  VERSION: 15
  MAX_LENGTH: 255
  ANNOTATION_TITLE: 127
  ANNOTATION_TYPE: 63
  DEPARTMENT: 31
  ROLE: 31
  TELEPHONE: 31
  X400: 63
  DATA_TYPE: 63
  TIME_PERIOD: 63
  MEAS_DIM_VALUE: 255
  OBS_VALUE: 255
  DIMENSION_TYPE: 15
  METADATA_TARGET_COMPONENTS: 63 
  TOKENS: 15
  VALUE_MAP: 127
  PERIODICITY: 63
  OFFSET: 63
  TOLERANCE: 63
  LANG: 63
REMOVED_SETTINGS:
  - FIESTA: []
  - FIESTA_MAXLENGTHS: []
