# Generated by Django 2.2.3 on 2019-09-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conceptscheme', '0002_auto_20190910_0437'),
        ('common', '0001_initial'),
        ('datastructure', '0001_initial'),
        ('registry', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='submitted_structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.SubmittedStructure'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organisation', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructure.DataStructure'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='submitted_structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.SubmittedStructure'),
        ),
        migrations.AddField(
            model_name='attributerelationship',
            name='attachment_group',
            field=models.ManyToManyField(related_name='_attributerelationship_attachment_group_+', to='datastructure.Group'),
        ),
        migrations.AddField(
            model_name='attributerelationship',
            name='attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastructure.Attribute'),
        ),
        migrations.AddField(
            model_name='attributerelationship',
            name='dimension',
            field=models.ManyToManyField(related_name='_attributerelationship_dimension_+', to='datastructure.Dimension'),
        ),
        migrations.AddField(
            model_name='attributerelationship',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datastructure.Group'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='data_structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastructure.DataStructure'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='concept_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_concept_identity_set', related_query_name='attribute_concept_identity', to='conceptscheme.Concept'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='concept_role',
            field=models.ManyToManyField(related_name='attribute_concept_role_set', related_query_name='attribute_concept_role', to='conceptscheme.Concept'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='local_representation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Representation'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructure.AttributeList'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['object_id'], name='datastructu_object__21184e_idx'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['concept_identity'], name='datastructu_concept_a45f48_idx'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['object_id', 'concept_identity'], name='datastructu_object__6513fd_idx'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['object_id', 'wrapper'], name='datastructu_object__f6be63_idx'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['concept_identity', 'wrapper'], name='datastructu_concept_a061d3_idx'),
        ),
        migrations.AddIndex(
            model_name='primarymeasure',
            index=models.Index(fields=['object_id', 'concept_identity', 'wrapper'], name='datastructu_object__7bcccb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='primarymeasure',
            unique_together={('object_id', 'concept_identity', 'wrapper')},
        ),
        migrations.AddIndex(
            model_name='groupdimension',
            index=models.Index(fields=['wrapper'], name='datastructu_wrapper_8d8b24_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdimension',
            index=models.Index(fields=['dimension_reference'], name='datastructu_dimensi_a93a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdimension',
            index=models.Index(fields=['wrapper', 'dimension_reference'], name='datastructu_wrapper_6e47ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdimension',
            unique_together={('wrapper', 'dimension_reference')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['object_id'], name='datastructu_object__73582d_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['data_structure'], name='datastructu_data_st_f63ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['object_id', 'data_structure'], name='datastructu_object__793060_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('object_id', 'data_structure')},
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['object_id'], name='datastructu_object__2ab523_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['concept_identity'], name='datastructu_concept_3bacf0_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['object_id', 'concept_identity'], name='datastructu_object__57d6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['object_id', 'wrapper'], name='datastructu_object__1bccc5_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['concept_identity', 'wrapper'], name='datastructu_concept_6dd225_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['object_id', 'concept_identity', 'wrapper'], name='datastructu_object__689b7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('object_id', 'concept_identity', 'wrapper')},
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['object_id'], name='datastructu_object__719a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['agency'], name='datastructu_agency__c05336_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['object_id', 'version'], name='datastructu_object__7215cf_idx'),
        ),
        migrations.AddIndex(
            model_name='datastructure',
            index=models.Index(fields=['object_id', 'agency', 'version'], name='datastructu_object__98abda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datastructure',
            unique_together={('object_id', 'agency', 'version')},
        ),
        migrations.AddIndex(
            model_name='attributerelationship',
            index=models.Index(fields=['attribute'], name='datastructu_attribu_07274c_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['object_id'], name='datastructu_object__013921_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['concept_identity'], name='datastructu_concept_fe9fec_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['object_id', 'concept_identity'], name='datastructu_object__07e506_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['object_id', 'wrapper'], name='datastructu_object__9f268a_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['concept_identity', 'wrapper'], name='datastructu_concept_db966f_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['object_id', 'concept_identity', 'wrapper'], name='datastructu_object__e5c8fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('object_id', 'concept_identity', 'wrapper')},
        ),
    ]
