# Generated by Django 3.0b1 on 2019-10-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_contact_party'),
        ('conceptscheme', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptscheme',
            name='submitted_structure',
            field=models.ManyToManyField(to='registry.SubmittedStructure', verbose_name='Submitted structures'),
        ),
        migrations.AddField(
            model_name='concept',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptscheme.ConceptScheme', verbose_name='Concept scheme'),
        ),
        migrations.AddField(
            model_name='concept',
            name='core_representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Representation', verbose_name='Core representation'),
        ),
        migrations.AddField(
            model_name='concept',
            name='iso_concept_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conceptscheme.ISOConceptReference', verbose_name='ISO concept'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptscheme.Concept', verbose_name='Concept'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='concept_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptscheme.ConceptScheme', verbose_name='Concept scheme'),
        ),
        migrations.AddIndex(
            model_name='conceptscheme',
            index=models.Index(fields=['agency', 'object_id', 'version'], name='conceptsche_agency__0a5fbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='conceptscheme',
            constraint=models.UniqueConstraint(fields=('agency', 'object_id', 'version'), name='conceptscheme_conceptscheme_unique_maintainable'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['container', 'object_id'], name='conceptsche_contain_4ebcaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('container', 'object_id'), name='conceptscheme_concept_unique_item'),
        ),
    ]
