# Generated by Django 2.2.3 on 2019-09-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('conceptscheme', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptscheme',
            name='submitted_structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.SubmittedStructure'),
        ),
        migrations.AddField(
            model_name='concept',
            name='core_representation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Representation'),
        ),
        migrations.AddField(
            model_name='concept',
            name='iso_concept_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptscheme.ISOConceptReference'),
        ),
        migrations.AddField(
            model_name='concept',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptscheme.ConceptScheme'),
        ),
    ]
