# Generated by Django 3.0b1 on 2019-10-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelist',
            name='submitted_structure',
            field=models.ManyToManyField(to='registry.SubmittedStructure', verbose_name='Submitted structures'),
        ),
        migrations.AddField(
            model_name='code',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.Codelist', verbose_name='Codelist'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codelist.Code', verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='codelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codelist.Codelist', verbose_name='Codelist'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['agency', 'object_id', 'version'], name='codelist_co_agency__cfefbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='codelist',
            constraint=models.UniqueConstraint(fields=('agency', 'object_id', 'version'), name='codelist_codelist_unique_maintainable'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['container', 'object_id'], name='codelist_co_contain_7a3c73_idx'),
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('container', 'object_id'), name='codelist_code_unique_item'),
        ),
    ]
