# Generated by Django 2.2.3 on 2019-09-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelist',
            name='submitted_structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.SubmittedStructure'),
        ),
        migrations.AddField(
            model_name='code',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.Codelist', verbose_name='Codelist'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['object_id'], name='codelist_co_object__3ebb31_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['agency'], name='codelist_co_agency__b97d68_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['object_id', 'version'], name='codelist_co_object__7d5c89_idx'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['object_id', 'agency', 'version'], name='codelist_co_object__238bd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codelist',
            unique_together={('object_id', 'agency', 'version')},
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['object_id'], name='codelist_co_object__ae00fa_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['wrapper'], name='codelist_co_wrapper_b4221a_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['wrapper', 'object_id'], name='codelist_co_wrapper_ef1ff4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('wrapper', 'object_id')},
        ),
    ]
