# Generated by Django 2.2.6 on 2019-10-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codelist', '0001_initial'),
        ('common', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelist',
            name='annotations',
            field=models.ManyToManyField(related_name='_codelist_annotations_+', to='common.Annotation', verbose_name='Annotations'),
        ),
        migrations.AddField(
            model_name='codelist',
            name='submitted_structure',
            field=models.ManyToManyField(to='registry.SubmittedStructure', verbose_name='Submitted structures'),
        ),
        migrations.AddField(
            model_name='code',
            name='annotations',
            field=models.ManyToManyField(related_name='_code_annotations_+', to='common.Annotation', verbose_name='Annotations'),
        ),
        migrations.AddField(
            model_name='code',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.Codelist', verbose_name='Codelist'),
        ),
        migrations.AddIndex(
            model_name='codelist',
            index=models.Index(fields=['agency', 'object_id', 'major', 'minor', 'patch'], name='codelist_co_agency__c6e4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='codelist',
            constraint=models.UniqueConstraint(fields=('agency', 'object_id', 'major', 'minor', 'patch'), name='unique_maintainable'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['container', 'object_id'], name='codelist_co_contain_7a3c73_idx'),
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('container', 'object_id'), name='unique_item'),
        ),
    ]
